apiVersion: v1
kind: Pod
metadata: 
  name: php-mysql-app
spec: 
  containers: 
    - 
      env: 
        - 
          name: MYSQL_USER
          valueFrom: 
            secretKeyRef: 
              key: username
              name: generic-secret-from-ltrl
        - 
          name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef: 
              key: password
              name: generic-secret-from-ltrl
      image: "php:latest"
      name: php-app
