apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: volumepod1
  name: volumepod
spec:
  containers:
  - image: centos
    name: volumepod
    volumeMounts:
      - mountPath: /centos1
        name: test
  volumes:
    - name: test
      emptyDir: {}
