apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  containers:
  - image: nginx
    name: test
    volumeMounts:
      - name: vol1
        mountPath: /usr/share/nginx/html
  volumes:
  - name: vol1
    emptyDir: {}
